__all__ = ["manifests", "samples"]

_samples_definitions = [
    [
        {
            "barcode": f"CTTTP01A1.0{n}",
            "cimac_id": f"CTTTP01A1.0{n}",
            "protocol_identifier": "test_trial",
            "manifest_id": "test_trial_pbmc1",
            "participant_id": "LOCAL 01",
            "sample_key": f"test_trial,LOCAL 01,TRIALGROUP {n}",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_priority": "1",
            "assay_type": "CyTOF",
            "biobank_id": "biobank",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Not Reported",
            "modified_time": 1609545600 + 86400 * n,
            "modified_timestamp": f"2021-01-02{n}00:00:00Z",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Mononuclear Cells",
            "sample_collection_procedure": "Blood Draw",
            "sample_manifest_type": "biofluid_cellular",
            "submitter": "user",
            "type_of_primary_container": "Sodium Heparin Tube",
            "type_of_sample": "Blood",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP01A2.0{n}",
            "cimac_id": f"CTTTP01A2.0{n}",
            "cohort_name": "Arm_Z",
            "collection_event_name": "Pre_Day_1_Cycle_2",
            "manifest_id": "test_trial_pbmc2",
            "participant_id": "LOCAL 01",
            "protocol_identifier": "test_trial",
            "sample_key": f"test_trial,LOCAL 01,BIOBANK {n}",
            "standardized_collection_event_name": "Pre_Day_1_Cycle_2",
            "status": "cimac_id_generated",
            "assay_priority": "1",
            "assay_type": "RNAseq",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "material_remaining": 1.0,
            "material_remaining_units": "Cells per Vial",
            "material_storage_condition": "LN",
            "material_used": 1.0,
            "material_used_units": "Cells per Vial",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "pbmc_recovery": 1.0,
            "pbmc_resting_period_used": "No",
            "pbmc_viability": 1.0,
            "processed_sample_concentration": "50",
            "processed_sample_concentration_units": "Cells per Vial",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "pbmc",
            "processed_sample_volume": 1.0,
            "processed_sample_volume_units": "Milliliters",
            "qc_comments": "",
            "quality_of_sample": "Pass",
            "residual_sample_use": "Sample Sent to Another Lab",
            "sample_collection_procedure": "Other",
            "sample_location": "Y",
            "sample_manifest_type": "biofluid_cellular",
            "sample_replacement": "Replacement Not Requested",
            "submitter": "user",
            "type_of_primary_container": "Sodium heparin",
            "type_of_sample": "Other",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP01A3.0{n}",
            "cimac_id": f"CTTTP01A3.0{n}",
            "cohort_name": "Arm_Z",
            "collection_event_name": "Baseline",
            "manifest_id": "test_trial_tissue_slide",
            "participant_id": "LOCAL 01",
            "protocol_identifier": "test_trial",
            "sample_key": f"test_trial,LOCAL 01,BIOBANK {n}",
            "standardized_collection_event_name": "Baseline",
            "status": "qc_complete",
            "assay_priority": "1",
            "assay_type": "mIF",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": n,
            "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
            "material_used_units": "Slides",
            "material_remaining_units": "Slides",
            "material_used": 1.0,
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": "35 PRE",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_quantity": 1.0,
            "processed_sample_type": "tissue_slide",
            "quality_of_sample": "Pass",
            "qc_comments": "",
            "sample_approved": True,
            "sample_collection_procedure": "Core Biopsy",
            "sample_location": "Y",
            "sample_manifest_type": "tissue_slides",
            "sample_replacement": "Replacement Not Requested",
            "submitter": "user",
            "type_of_sample": "Tumor Tissue",
            "type_of_tumor_sample": "Primary Tumor",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP02A1.0{n}",
            "cimac_id": f"CTTTP02A1.0{n}",
            "cohort_name": "Arm_A",
            "manifest_id": "test_trial_other_tumor_rna",
            "participant_id": "LOCAL 02",
            "protocol_identifier": "test_trial",
            "recorded_collection_event_name": "Start",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_type": "RNAseq",
            "assay_priority": "1",
            "biobank_id": "biobank",
            "box_number": "X",
            "core_number": "Not Reported",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_derivative": "RNA",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Other",
            "processed_sample_quantity": 1.0,
            "sample_collection_procedure": "Bone Marrow Core Biopsy",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_derivative_concentration": "1.0",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_key": f"test_trial,LOCAL 02,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "tissue_nucleic_acid",
            "submitter": "user",
            "type_of_sample": "Tumor Tissue",
            "type_of_tumor_sample": "Primary Tumor",
            "type_of_primary_container": "Not Reported",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP02A2.0{n}",
            "cimac_id": f"CTTTP02A2.0{n}",
            "cohort_name": "Arm_A",
            "collection_event_name": "Pre_Day_1_Cycle_2",
            "manifest_id": "test_trial_normal_dna",
            "participant_id": "LOCAL 02",
            "protocol_identifier": "test_trial",
            "status": "qc_complete",
            "assay_priority": "1",
            "assay_type": "WES",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_derivative": "Germline DNA",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_quantity": 1.0,
            "processed_sample_type": "normal_tissue_dna",
            "qc_comments": "",
            "sample_collection_procedure": "Blood Draw",
            "sample_derivative_concentration": "1.0",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_approved": True,
            "sample_location": "Y",
            "sample_key": f"test_trial,LOCAL 01,BIOBANK {n}",
            "sample_manifest_type": "tissue_nucleic_acid",
            "standardized_collection_event_name": "Baseline",
            "submitter": "user",
            "type_of_sample": "Blood",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP02A3.0{n}",
            "cimac_id": f"CTTTP02A3.0{n}",
            "cohort_name": "Arm_A",
            "collection_event_name": "Baseline",
            "manifest_id": "test_trial_plasma1",
            "participant_id": "LOCAL 02",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Baseline",
            "status": "qc_complete",
            "assay_priority": "1",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "material_used_units": "Microliters",
            "material_remaining_units": "Microliters",
            "material_storage_condition": "(-80)oC",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "plasma",
            "processed_sample_volume_units": "Milliliters",
            "qc_comments": "",
            "quality_of_sample": "Pass",
            "sample_replacement": "Replacement Not Requested",
            "sample_approved": True,
            "sample_collection_procedure": "Blood Draw",
            "sample_key": f"test_trial,LOCAL 02,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "biofluid_plasma",
            "submitter": "user",
            "type_of_primary_container": "Other",
            "type_of_sample": "Blood",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP03A1.0{n}",
            "cimac_id": f"CTTTP03A1.0{n}",
            "manifest_id": "test_trial_plasma2",
            "participant_id": "LOCAL 03",
            "protocol_identifier": "test_trial",
            "recorded_collection_event_name": "Start",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_type": "Olink",
            "assay_priority": "1",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Plasma",
            "processed_sample_volume_units": "Microliters",
            "sample_collection_procedure": "Blood Draw",
            "sample_key": f"test_trial,LOCAL 03,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "biofluid_plasma",
            "submitter": "user",
            "type_of_primary_container": "Sodium Heparin Tube",
            "type_of_sample": "Blood",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP03A2.0{n}",
            "cimac_id": f"CTTTP03A2.0{n}",
            "cohort_name": "Arm_Z",
            "collection_event_name": "On_Treatment",
            "manifest_id": "test_trial_tumor_rna",
            "participant_id": "LOCAL 03",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Pre_Day_1_Cycle_2",
            "status": "cimac_id_generated",
            "a260_or_a230_value": 1.0,
            "a260_or_a280_value": 1.0,
            "assay_priority": "1",
            "assay_type": "WES",
            "biobank_id": "biobank",
            "box_number": "X",
            "core_number": "1.0",
            "din_value": 1.0,
            "entry_number": 1,
            "fixation_or_stabilization_type": "Frozen Specimen",
            "material_remaining": 1.0,
            "material_remaining_units": "Not Reported",
            "material_storage_condition": "Not Reported",
            "material_used": 1.0,
            "material_used_units": "Not Reported",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_derivative": "Tumor RNA",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_quantity": 1.0,
            "processed_sample_type": "tumor_tissue_dna",
            "qc_comments": "",
            "quality_of_sample": "Pass",
            "residual_sample_use": "Not Reported",
            "sample_collection_procedure": "Not Reported",
            "sample_derivative_concentration": "1",
            "sample_derivative_concentration_units": "Not Reported",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Not Reported",
            "sample_key": f"test_trial,LOCAL 03,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "tissue_nucleic_acid",
            "sample_replacement": "Not Reported",
            "submitter": "user",
            "type_of_sample": "Tumor Tissue",
            "type_of_tumor_sample": "Not Reported",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP03A3.0{n}",
            "cimac_id": f"CTTTP03A3.0{n}",
            "cohort_name": "Arm_Z",
            "collection_event_name": "Baseline",
            "manifest_id": "test_trial:TTTP03:BIOBANK {n}",
            "participant_id": "LOCAL 03",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_priority": "1",
            "assay_type": "WES",
            "biobank_id": "biobank",
            "box_number": "X",
            "comments": '{"Processed sample type": "Buffy Coat"}',
            "entry_number": 1,
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "processed_sample_derivative": "Germline DNA",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "normal_blood_dna",
            "processed_sample_quantity": 1.0,
            "processed_sample_volume": 1.0,
            "processed_sample_volume_units": "Milliliters",
            "qc_comments": '{"Processed sample type": "Buffy Coat"}',
            "sample_collection_procedure": "Blood Draw",
            "sample_derivative_concentration": "1",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_key": f"test_trial,LOCAL 03,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "blood_nucleic_acid",
            "submitter": "user",
            "type_of_primary_container": "Not Reported",
            "type_of_sample": "Blood",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP04A1.0{n}",
            "cimac_id": f"CTTTP04A1.0{n}",
            "manifest_id": "test_trial_fixed_slide",
            "participant_id": "LOCAL 04",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_type": "WES",
            "assay_priority": "1",
            "biobank_id": "biobank",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": "Not Reported",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Fixed Slide",
            "processed_sample_quantity": 1.0,
            "processed_sample_derivative": "DNA",
            "sample_collection_procedure": "Core Biopsy",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_derivative_concentration": "1",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_manifest_type": "tissue_nucleic_acid",
            "protocol_identifier": "test_trial",
            "sample_key": f"test_trial,LOCAL 04,BIOBANK {n}",
            "submitter": "user",
            "type_of_sample": "Tumor Tissue",
            "type_of_tumor_sample": "Primary Tumor",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP04A2.0{n}",
            "cimac_id": f"CTTTP04A2.0{n}",
            "cohort_name": "Arm_A",
            "collection_event_name": "On_Treatment",
            "manifest_id": "test_trial_tumor_dna",
            "participant_id": "LOCAL 04",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Pre_Day_1_Cycle_2",
            "status": "qc_complete",
            "assay_priority": "1",
            "assay_type": "WES",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Archival FFPE",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_derivative": "Tumor DNA",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_quantity": 1.0,
            "processed_sample_type": "tumor_tissue_dna",
            "qc_comments": "",
            "sample_approved": True,
            "sample_collection_procedure": "Core Biopsy",
            "sample_derivative_concentration": "1.0",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_location": "Y",
            "sample_key": f"test_trial,LOCAL 04,BIOBANK {n}",
            "sample_manifest_type": "tissue_nucleic_acid",
            "submitter": "user",
            "type_of_sample": "Tumor Tissue",
            "type_of_tumor_sample": "Primary Tumor",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP04A3.0{n}",
            "cimac_id": f"CTTTP04A3.0{n}",
            "cohort_name": "Arm_A",
            "collection_event_name": "Baseline",
            "manifest_id": "test_trial_h_and_e",
            "participant_id": "LOCAL 04",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Baseline",
            "status": "qc_complete",
            "assay_priority": "1",
            "assay_type": "H&E",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
            "material_remaining": 1.0,
            "material_remaining_units": "Slides",
            "material_storage_condition": "4oC",
            "material_used": 1.0,
            "material_used_units": "Slides",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_quantity": 1.0,
            "processed_sample_type": "h_and_e",
            "qc_comments": "",
            "quality_of_sample": "Pass",
            "sample_collection_procedure": "Core Biopsy",
            "sample_replacement": "Replacement Not Requested",
            "sample_approved": True,
            "sample_location": "Y",
            "sample_key": f"test_trial,LOCAL 04,BIOBANK {n}",
            "sample_manifest_type": "tissue_h_and_e",
            "submitter": "user",
            "type_of_sample": "Tumor Tissue",
            "type_of_tumor_sample": "Metastatic Tumor",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP05A1.0{n}",
            "cimac_id": f"CTTTP05A1.0{n}",
            "cohort_name": "Arm_Z",
            "manifest_id": "test_trial_cell_pellet",
            "participant_id": "LOCAL 05",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_priority": "1",
            "assay_type": "WES",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Not Reported",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_derivative": "Germline DNA",
            "processed_sample_quantity": 1.0,
            "processed_sample_type": "Cell Pellet",
            "processed_sample_volume": 1.0,
            "processed_sample_volume_units": "Not Reported",
            "qc_comments": "recipient",
            "sample_collection_procedure": "Blood Draw",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Not Reported",
            "sample_derivative_concentration": "0",
            "sample_derivative_concentration_units": "Not Reported",
            "sample_key": f"test_trial,LOCAL 05,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "blood_nucleic_acid",
            "submitter": "user",
            "type_of_primary_container": "Not Reported",
            "type_of_sample": "Other",
            "type_of_tumor_sample": "Other",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP05A2.0{n}",
            "cimac_id": f"CTTTP05A2.0{n}",
            "manifest_id": "test_trial_whole_blood",
            "participant_id": "LOCAL 05",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Pre_Day_1_Cycle_2",
            "status": "cimac_id_generated",
            "assay_priority": "1",
            "assay_type": "WES",
            "biobank_id": "biobank",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Not Reported",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": "Not Reported",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Whole Blood",
            "processed_sample_derivative": "Germline DNA",
            "sample_collection_procedure": "Blood Draw",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_derivative_concentration": "1",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_key": f"test_trial,LOCAL 05,BIOBANK {n}",
            "sample_manifest_type": "blood_nucleic_acid",
            "submitter": "user",
            "type_of_sample": "Blood",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP05A3.0{n}",
            "cimac_id": f"CTTTP05A3.0{n}",
            "cohort_name": "Arm_Z",
            "manifest_id": "test_trial_buffy_coat",
            "participant_id": "LOCAL 05",
            "protocol_identifier": "test_trial",
            "recorded_collection_event_name": "Not Reported",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "a260_or_a280_value": 1.0,
            "assay_type": "WES",
            "assay_priority": "1",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "sample_collection_procedure": "Blood Draw",
            "fixation_or_stabilization_type": "Not Reported",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Buffy Coat",
            "processed_sample_volume": 1.0,
            "processed_sample_volume_units": "Microliters",
            "processed_sample_quantity": 1.0,
            "processed_sample_derivative": "Germline DNA",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_derivative_concentration": "1.0",
            "sample_derivative_concentration_units": "Micrograms per Microliter",
            "sample_key": f"test_trial,LOCAL 05,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "blood_nucleic_acid",
            "submitter": "user",
            "type_of_primary_container": "EDTA Tube",
            "type_of_sample": "Blood",
            "type_of_tumor_sample": "Other",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": "CTTTP06A1.01",
            "cimac_id": "CTTTP06A1.01",
            "cohort_name": "Arm_Z",
            "manifest_id": "test_trial_biofluid_cellular_nucleic_acid",
            "participant_id": "LOCAL 06",
            "protocol_identifier": "test_trial",
            "recorded_collection_event_name": "Not Reported",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_type": "TCR",
            "assay_priority": "1",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Not Reported",
            "material_storage_condition": "(-80)oC",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "pbmc_resting_period_used": "Yes",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Mononuclear Cells",
            "processed_sample_volume": 1.0,
            "processed_sample_volume_units": "Milliliters",
            "processed_sample_quantity": 1.0,
            "processed_sample_derivative": "DNA",
            "sample_collection_procedure": "Blood Draw",
            "sample_derivative_concentration": "1",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_key": f"test_trial,LOCAL 06,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "biofluid_cellular_nucleic_acid",
            "submitter": "user",
            "type_of_sample": "Blood",
            "type_of_primary_container": "Sodium Heparin Tube",
        }
        for n in range(3)
    ],
]

samples = [entry for group in _samples_definitions for entry in group]

_manifests_to_make = {s["manifest_id"] for s in samples}
manifests = [
    {
        "biobank_id": "biobank",
        "courier": "Inter-Site Delivery",
        "date_received": "2021-01-05 00:00:00",
        "date_shipped": "2021-01-03 00:00:00",
        "quality_of_shipment": "Specimen shipment received in good condition",
        "receiving_party": "Adaptive",
        "ship_from": "from",
        "ship_to": "to",
        "shipping_condition": "Frozen_Shipper",
        "tracking_number": "X",
        "submitter": "user",
        "modified_time": 1609459200 + 86400 * 2,
        "modified_timestamp": "2021-01-05T00:00:00Z",
        "manifest_id": manifest,
        "barcode": manifest,
    }
    for manifest in _manifests_to_make
]

for n, _ in enumerate(manifests):
    manifests[n]["samples"] = [
        s for s in samples if s.get("manifest_id") == manifests[n]["manifest_id"]
    ]

    if all(s.get("status") == "cimac_id_generated" for s in manifests[n]["samples"]):
        manifests[n]["status"] = "draft"

    elif all(s.get("status") in [None, "qc_complete"] for s in manifests[n]["samples"]):
        if manifests[n]["samples"][0].get("status") == "qc_complete":
            manifests[n]["status"] = "qc_complete"
        manifests[n]["account_number"] = "AccN"

    else:
        raise AssertionError(
            f"Bad data, all status should be the same for manifest {manifests[n]['manifest_id']}:\n"
            + str([s.get("status") for s in manifests[n]["samples"]])
        )
