__all__ = ["manifests", "samples"]

from copy import deepcopy


_samples_definitions = [
    [
        {
            "barcode": f"CTTTP01A1.0{n}",
            "cimac_id": f"CTTTP01A1.0{n}",
            "protocol_identifier": "test_trial",
            "manifest_id": "test_trial_pbmc1",
            "participant_id": "LOCAL 01",
            "sample_key": f"test_trial,LOCAL 01,TRIALGROUP {n}",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_priority": "1",
            "assay_type": "CyTOF",
            "biobank_id": "biobank",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Not Reported",
            "modified_time": 1609545600 + 86400 * n,
            "modified_timestamp": f"2021-01-02{n}00:00:00Z",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Mononuclear Cells",
            "sample_collection_procedure": "Blood Draw",
            "sample_manifest_type": "biofluid_cellular",
            "submitter": "user",
            "type_of_primary_container": "Sodium Heparin Tube",
            "type_of_sample": "Blood",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP01A2.0{n}",
            "cimac_id": f"CTTTP01A2.0{n}",
            "cohort_name": "Arm_Z",
            "collection_event_name": "Pre_Day_1_Cycle_2",
            "manifest_id": "test_trial_pbmc2",
            "participant_id": "LOCAL 01",
            "protocol_identifier": "test_trial",
            "sample_key": f"test_trial,LOCAL 01,BIOBANK {n}",
            "standardized_collection_event_name": "Pre_Day_1_Cycle_2",
            "status": "cimac_id_generated",
            "assay_priority": "1",
            "assay_type": "RNAseq",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "material_remaining": 1.0,
            "material_remaining_units": "Cells per Vial",
            "material_storage_condition": "LN",
            "material_used": 1.0,
            "material_used_units": "Cells per Vial",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "pbmc_recovery": 1.0,
            "pbmc_resting_period_used": "No",
            "pbmc_viability": 1.0,
            "processed_sample_concentration": "50",
            "processed_sample_concentration_units": "Cells per Vial",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "pbmc",
            "processed_sample_volume": 1.0,
            "processed_sample_volume_units": "Milliliters",
            "qc_comments": "",
            "quality_of_sample": "Pass",
            "residual_sample_use": "Sample Sent to Another Lab",
            "sample_collection_procedure": "Other",
            "sample_location": "Y",
            "sample_manifest_type": "biofluid_cellular",
            "sample_replacement": "Replacement Not Requested",
            "submitter": "user",
            "type_of_primary_container": "Sodium heparin",
            "type_of_sample": "Other",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP01A3.0{n}",
            "cimac_id": f"CTTTP01A3.0{n}",
            "cohort_name": "Arm_Z",
            "collection_event_name": "Baseline",
            "manifest_id": "test_trial_tissue_slide",
            "participant_id": "LOCAL 01",
            "protocol_identifier": "test_trial",
            "sample_key": f"test_trial,LOCAL 01,BIOBANK {n}",
            "standardized_collection_event_name": "Baseline",
            "status": "qc_complete",
            "assay_priority": "1",
            "assay_type": "mIF",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": n,
            "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
            "material_used_units": "Slides",
            "material_remaining_units": "Slides",
            "material_used": 1.0,
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": "35 PRE",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_quantity": 1.0,
            "processed_sample_type": "tissue_slide",
            "quality_of_sample": "Pass",
            "qc_comments": "",
            "sample_approved": True,
            "sample_collection_procedure": "Core Biopsy",
            "sample_location": "Y",
            "sample_manifest_type": "tissue_slides",
            "sample_replacement": "Replacement Not Requested",
            "submitter": "user",
            "type_of_sample": "Tumor Tissue",
            "type_of_tumor_sample": "Primary Tumor",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP02A1.0{n}",
            "cimac_id": f"CTTTP02A1.0{n}",
            "cohort_name": "Arm_A",
            "manifest_id": "test_trial_other_tumor_rna",
            "participant_id": "LOCAL 02",
            "protocol_identifier": "test_trial",
            "recorded_collection_event_name": "Start",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_type": "RNAseq",
            "assay_priority": "1",
            "biobank_id": "biobank",
            "box_number": "X",
            "core_number": "Not Reported",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_derivative": "RNA",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Other",
            "processed_sample_quantity": 1.0,
            "sample_collection_procedure": "Bone Marrow Core Biopsy",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_derivative_concentration": "1.0",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_key": f"test_trial,LOCAL 02,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "tissue_nucleic_acid",
            "submitter": "user",
            "type_of_sample": "Tumor Tissue",
            "type_of_tumor_sample": "Primary Tumor",
            "type_of_primary_container": "Not Reported",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP02A2.0{n}",
            "cimac_id": f"CTTTP02A2.0{n}",
            "cohort_name": "Arm_A",
            "collection_event_name": "Pre_Day_1_Cycle_2",
            "manifest_id": "test_trial_normal_dna",
            "participant_id": "LOCAL 02",
            "protocol_identifier": "test_trial",
            "status": "qc_complete",
            "assay_priority": "1",
            "assay_type": "WES",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_derivative": "Germline DNA",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_quantity": 1.0,
            "processed_sample_type": "normal_tissue_dna",
            "qc_comments": "",
            "sample_collection_procedure": "Blood Draw",
            "sample_derivative_concentration": "1.0",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_approved": True,
            "sample_location": "Y",
            "sample_key": f"test_trial,LOCAL 01,BIOBANK {n}",
            "sample_manifest_type": "tissue_nucleic_acid",
            "standardized_collection_event_name": "Baseline",
            "submitter": "user",
            "type_of_sample": "Blood",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP02A3.0{n}",
            "cimac_id": f"CTTTP02A3.0{n}",
            "cohort_name": "Arm_A",
            "collection_event_name": "Baseline",
            "manifest_id": "test_trial_plasma1",
            "participant_id": "LOCAL 02",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Baseline",
            "status": "qc_complete",
            "assay_priority": "1",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "material_used_units": "Microliters",
            "material_remaining_units": "Microliters",
            "material_storage_condition": "(-80)oC",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "plasma",
            "processed_sample_volume_units": "Milliliters",
            "qc_comments": "",
            "quality_of_sample": "Pass",
            "sample_replacement": "Replacement Not Requested",
            "sample_approved": True,
            "sample_collection_procedure": "Blood Draw",
            "sample_key": f"test_trial,LOCAL 02,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "biofluid_plasma",
            "submitter": "user",
            "type_of_primary_container": "Other",
            "type_of_sample": "Blood",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP03A1.0{n}",
            "cimac_id": f"CTTTP03A1.0{n}",
            "manifest_id": "test_trial_plasma2",
            "participant_id": "LOCAL 03",
            "protocol_identifier": "test_trial",
            "recorded_collection_event_name": "Start",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_type": "Olink",
            "assay_priority": "1",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Plasma",
            "processed_sample_volume_units": "Microliters",
            "sample_collection_procedure": "Blood Draw",
            "sample_key": f"test_trial,LOCAL 03,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "biofluid_plasma",
            "submitter": "user",
            "type_of_primary_container": "Sodium Heparin Tube",
            "type_of_sample": "Blood",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP03A2.0{n}",
            "cimac_id": f"CTTTP03A2.0{n}",
            "cohort_name": "Arm_Z",
            "collection_event_name": "On_Treatment",
            "manifest_id": "test_trial_tumor_rna",
            "participant_id": "LOCAL 03",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Pre_Day_1_Cycle_2",
            "status": "cimac_id_generated",
            "a260_or_a230_value": 1.0,
            "a260_or_a280_value": 1.0,
            "assay_priority": "1",
            "assay_type": "WES",
            "biobank_id": "biobank",
            "box_number": "X",
            "core_number": "1.0",
            "din_value": 1.0,
            "entry_number": 1,
            "fixation_or_stabilization_type": "Frozen Specimen",
            "material_remaining": 1.0,
            "material_remaining_units": "Not Reported",
            "material_storage_condition": "Not Reported",
            "material_used": 1.0,
            "material_used_units": "Not Reported",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_derivative": "Tumor RNA",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_quantity": 1.0,
            "processed_sample_type": "tumor_tissue_dna",
            "qc_comments": "",
            "quality_of_sample": "Pass",
            "residual_sample_use": "Not Reported",
            "sample_collection_procedure": "Not Reported",
            "sample_derivative_concentration": "1",
            "sample_derivative_concentration_units": "Not Reported",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Not Reported",
            "sample_key": f"test_trial,LOCAL 03,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "tissue_nucleic_acid",
            "sample_replacement": "Not Reported",
            "submitter": "user",
            "type_of_sample": "Tumor Tissue",
            "type_of_tumor_sample": "Not Reported",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP03A3.0{n}",
            "cimac_id": f"CTTTP03A3.0{n}",
            "cohort_name": "Arm_Z",
            "collection_event_name": "Baseline",
            "manifest_id": "test_trial:TTTP03:BIOBANK {n}",
            "participant_id": "LOCAL 03",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_priority": "1",
            "assay_type": "WES",
            "biobank_id": "biobank",
            "box_number": "X",
            "comments": '{"Processed sample type": "Buffy Coat"}',
            "entry_number": 1,
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "processed_sample_derivative": "Germline DNA",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "normal_blood_dna",
            "processed_sample_quantity": 1.0,
            "processed_sample_volume": 1.0,
            "processed_sample_volume_units": "Milliliters",
            "qc_comments": '{"Processed sample type": "Buffy Coat"}',
            "sample_collection_procedure": "Blood Draw",
            "sample_derivative_concentration": "1",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_key": f"test_trial,LOCAL 03,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "blood_nucleic_acid",
            "submitter": "user",
            "type_of_primary_container": "Not Reported",
            "type_of_sample": "Blood",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP04A1.0{n}",
            "cimac_id": f"CTTTP04A1.0{n}",
            "manifest_id": "test_trial_fixed_slide",
            "participant_id": "LOCAL 04",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_type": "WES",
            "assay_priority": "1",
            "biobank_id": "biobank",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": "Not Reported",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Fixed Slide",
            "processed_sample_quantity": 1.0,
            "processed_sample_derivative": "DNA",
            "sample_collection_procedure": "Core Biopsy",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_derivative_concentration": "1",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_manifest_type": "tissue_nucleic_acid",
            "protocol_identifier": "test_trial",
            "sample_key": f"test_trial,LOCAL 04,BIOBANK {n}",
            "submitter": "user",
            "type_of_sample": "Tumor Tissue",
            "type_of_tumor_sample": "Primary Tumor",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP04A2.0{n}",
            "cimac_id": f"CTTTP04A2.0{n}",
            "cohort_name": "Arm_A",
            "collection_event_name": "On_Treatment",
            "manifest_id": "test_trial_tumor_dna",
            "participant_id": "LOCAL 04",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Pre_Day_1_Cycle_2",
            "status": "qc_complete",
            "assay_priority": "1",
            "assay_type": "WES",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Archival FFPE",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_derivative": "Tumor DNA",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_quantity": 1.0,
            "processed_sample_type": "tumor_tissue_dna",
            "qc_comments": "",
            "sample_approved": True,
            "sample_collection_procedure": "Core Biopsy",
            "sample_derivative_concentration": "1.0",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_location": "Y",
            "sample_key": f"test_trial,LOCAL 04,BIOBANK {n}",
            "sample_manifest_type": "tissue_nucleic_acid",
            "submitter": "user",
            "type_of_sample": "Tumor Tissue",
            "type_of_tumor_sample": "Primary Tumor",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP04A3.0{n}",
            "cimac_id": f"CTTTP04A3.0{n}",
            "cohort_name": "Arm_A",
            "collection_event_name": "Baseline",
            "manifest_id": "test_trial_h_and_e",
            "participant_id": "LOCAL 04",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Baseline",
            "status": "qc_complete",
            "assay_priority": "1",
            "assay_type": "H&E",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
            "material_remaining": 1.0,
            "material_remaining_units": "Slides",
            "material_storage_condition": "4oC",
            "material_used": 1.0,
            "material_used_units": "Slides",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_quantity": 1.0,
            "processed_sample_type": "h_and_e",
            "qc_comments": "",
            "quality_of_sample": "Pass",
            "sample_collection_procedure": "Core Biopsy",
            "sample_replacement": "Replacement Not Requested",
            "sample_approved": True,
            "sample_location": "Y",
            "sample_key": f"test_trial,LOCAL 04,BIOBANK {n}",
            "sample_manifest_type": "tissue_h_and_e",
            "submitter": "user",
            "type_of_sample": "Tumor Tissue",
            "type_of_tumor_sample": "Metastatic Tumor",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP05A1.0{n}",
            "cimac_id": f"CTTTP05A1.0{n}",
            "cohort_name": "Arm_Z",
            "manifest_id": "test_trial_cell_pellet",
            "participant_id": "LOCAL 05",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_priority": "1",
            "assay_type": "WES",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Not Reported",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_derivative": "Germline DNA",
            "processed_sample_quantity": 1.0,
            "processed_sample_type": "Cell Pellet",
            "processed_sample_volume": 1.0,
            "processed_sample_volume_units": "Not Reported",
            "qc_comments": "recipient",
            "sample_collection_procedure": "Blood Draw",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Not Reported",
            "sample_derivative_concentration": "0",
            "sample_derivative_concentration_units": "Not Reported",
            "sample_key": f"test_trial,LOCAL 05,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "blood_nucleic_acid",
            "submitter": "user",
            "type_of_primary_container": "Not Reported",
            "type_of_sample": "Other",
            "type_of_tumor_sample": "Other",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP05A2.0{n}",
            "cimac_id": f"CTTTP05A2.0{n}",
            "manifest_id": "test_trial_whole_blood",
            "participant_id": "LOCAL 05",
            "protocol_identifier": "test_trial",
            "standardized_collection_event_name": "Pre_Day_1_Cycle_2",
            "status": "cimac_id_generated",
            "assay_priority": "1",
            "assay_type": "WES",
            "biobank_id": "biobank",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Not Reported",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": "Not Reported",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Whole Blood",
            "processed_sample_derivative": "Germline DNA",
            "sample_collection_procedure": "Blood Draw",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_derivative_concentration": "1",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_key": f"test_trial,LOCAL 05,BIOBANK {n}",
            "sample_manifest_type": "blood_nucleic_acid",
            "submitter": "user",
            "type_of_sample": "Blood",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": f"CTTTP05A3.0{n}",
            "cimac_id": f"CTTTP05A3.0{n}",
            "cohort_name": "Arm_Z",
            "manifest_id": "test_trial_buffy_coat",
            "participant_id": "LOCAL 05",
            "protocol_identifier": "test_trial",
            "recorded_collection_event_name": "Not Reported",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "a260_or_a280_value": 1.0,
            "assay_type": "WES",
            "assay_priority": "1",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "sample_collection_procedure": "Blood Draw",
            "fixation_or_stabilization_type": "Not Reported",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Buffy Coat",
            "processed_sample_volume": 1.0,
            "processed_sample_volume_units": "Microliters",
            "processed_sample_quantity": 1.0,
            "processed_sample_derivative": "Germline DNA",
            "sample_derivative_volume": 1.0,
            "sample_derivative_volume_units": "Microliters",
            "sample_derivative_concentration": "1.0",
            "sample_derivative_concentration_units": "Micrograms per Microliter",
            "sample_key": f"test_trial,LOCAL 05,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "blood_nucleic_acid",
            "submitter": "user",
            "type_of_primary_container": "EDTA Tube",
            "type_of_sample": "Blood",
            "type_of_tumor_sample": "Other",
        }
        for n in range(3)
    ],
    [
        {
            "barcode": "CTTTP06A1.01",
            "cimac_id": "CTTTP06A1.01",
            "cohort_name": "Arm_Z",
            "manifest_id": "test_trial_biofluid_cellular_nucleic_acid",
            "participant_id": "LOCAL 06",
            "protocol_identifier": "test_trial",
            "recorded_collection_event_name": "Not Reported",
            "standardized_collection_event_name": "Baseline",
            "status": "cimac_id_generated",
            "assay_type": "TCR",
            "assay_priority": "1",
            "biobank_id": "biobank",
            "box_number": "X",
            "entry_number": 1,
            "fixation_or_stabilization_type": "Not Reported",
            "material_storage_condition": "(-80)oC",
            "modified_time": 1609459200 + 86400 * n,
            "modified_timestamp": f"2021-01-0{n}T00:00:00Z",
            "parent_sample_id": f"TRIALGROUP {n}",
            "pbmc_resting_period_used": "Yes",
            "processed_sample_id": f"BIOBANK {n}",
            "processed_sample_type": "Mononuclear Cells",
            "processed_sample_volume": 1.0,
            "processed_sample_volume_units": "Milliliters",
            "processed_sample_quantity": 1.0,
            "processed_sample_derivative": "DNA",
            "sample_collection_procedure": "Blood Draw",
            "sample_derivative_concentration": "1",
            "sample_derivative_concentration_units": "Nanogram per Microliter",
            "sample_key": f"test_trial,LOCAL 06,BIOBANK {n}",
            "sample_location": "Y",
            "sample_manifest_type": "biofluid_cellular_nucleic_acid",
            "submitter": "user",
            "type_of_sample": "Blood",
            "type_of_primary_container": "Sodium Heparin Tube",
        }
        for n in range(3)
    ],
]

samples = [entry for group in _samples_definitions for entry in group]

_manifests_to_make = {s["manifest_id"] for s in samples}
manifests = [
    {
        "biobank_id": "biobank",
        "courier": "Inter-Site Delivery",
        "date_received": "2021-01-05 00:00:00",
        "date_shipped": "2021-01-03 00:00:00",
        "quality_of_shipment": "Specimen shipment received in good condition",
        "receiving_party": "Adaptive",
        "ship_from": "from",
        "ship_to": "to",
        "shipping_condition": "Frozen_Shipper",
        "tracking_number": "X",
        "submitter": "user",
        "modified_time": 1609459200 + 86400 * 2,
        "modified_timestamp": "2021-01-05T00:00:00Z",
        "manifest_id": manifest,
        "barcode": manifest,
        "excluded": False,
    }
    for manifest in _manifests_to_make
]

for n, _ in enumerate(manifests):
    manifests[n]["samples"] = [
        s for s in samples if s.get("manifest_id") == manifests[n]["manifest_id"]
    ]

    if all(s.get("status") == "cimac_id_generated" for s in manifests[n]["samples"]):
        manifests[n]["status"] = "draft"

    elif all(s.get("status") in [None, "qc_complete"] for s in manifests[n]["samples"]):
        if manifests[n]["samples"][0].get("status") == "qc_complete":
            manifests[n]["status"] = "qc_complete"
        manifests[n]["account_number"] = "AccN"

    else:
        raise AssertionError(
            f"Bad data, all status should be the same for manifest {manifests[n]['manifest_id']}:\n"
            + str([s.get("status") for s in manifests[n]["samples"]])
        )

manifests.append(deepcopy(manifests[-1]))
manifests[-1]["excluded"] = True

manifests.append(
    {
        "manifest_id": "test_trial_H&E",
        "receiving_party": "Adaptive",
        "courier": "Inter-Site Delivery",
        "shipping_condition": "Ambient",
        "quality_of_shipment": "Specimen shipment received in good condition",
        "account_number": "X",
        "status": "qc_complete",
        "biobank_id": "biobank",
        "barcode": "test_trial_H&E",
        "excluded": False,
        "submitter": "user",
        "reason": "Create excluded field for existing Manifests",
        "event": "manual_update",
        "modified_time": 1609459200 + 86400 * 2,
        "modified_timestamp": "2021-01-05T00:00:00Z",
        "samples": [
            {
                "entry_number": 21,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 07",
                "processed_sample_id": "BIOBANK 01",
                "cimac_id": "CTTTP5K1F.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 07,BIOBANK 01",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTP5K1F.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 23,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 08",
                "processed_sample_id": "BIOBANK 02",
                "cimac_id": "CTTT2B5RL.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 08,BIOBANK 02",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTT2B5RL.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 35,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 09",
                "processed_sample_id": "BIOBANK 03",
                "cimac_id": "CTTT98C2Q.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 09,BIOBANK 03",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTT98C2Q.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 1,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 10",
                "processed_sample_id": "BIOBANK 04",
                "cimac_id": "CTTTECQYC.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 10,BIOBANK 04",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTECQYC.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 11,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 11",
                "processed_sample_id": "BIOBANK 05",
                "cimac_id": "CTTTLRQE1.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 11,BIOBANK 05",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTLRQE1.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 25,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 12",
                "processed_sample_id": "BIOBANK 06",
                "cimac_id": "CTTTKCYGM.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 12,BIOBANK 06",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTKCYGM.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 36,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 13",
                "processed_sample_id": "BIOBANK 07",
                "cimac_id": "CTTT8NRIF.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 13,BIOBANK 07",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTT8NRIF.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 2,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 14",
                "processed_sample_id": "BIOBANK 08",
                "cimac_id": "CTTT8WJMN.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 14,BIOBANK 08",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTT8WJMN.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 12,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 15",
                "processed_sample_id": "BIOBANK 09",
                "cimac_id": "CTTTBP7IS.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 15,BIOBANK 09",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTBP7IS.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 26,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 16",
                "processed_sample_id": "BIOBANK 10",
                "cimac_id": "CTTT9Y232.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 16,BIOBANK 10",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTT9Y232.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 37,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 17",
                "processed_sample_id": "BIOBANK 11",
                "cimac_id": "CTTTJCOJW.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 17,BIOBANK 11",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTJCOJW.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 3,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 18",
                "processed_sample_id": "BIOBANK 12",
                "cimac_id": "CTTTQS2VM.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 18,BIOBANK 12",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTQS2VM.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 13,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 19",
                "processed_sample_id": "BIOBANK 13",
                "cimac_id": "CTTTWZUQ1.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 19,BIOBANK 13",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTWZUQ1.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 27,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 20",
                "processed_sample_id": "BIOBANK 14",
                "cimac_id": "CTTTH8HBL.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 20,BIOBANK 14",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTH8HBL.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 40,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 21",
                "processed_sample_id": "BIOBANK 15",
                "cimac_id": "CTTTC0TGL.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 21,BIOBANK 15",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTC0TGL.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 4,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 22",
                "processed_sample_id": "BIOBANK 16",
                "cimac_id": "CTTTBAAAJ.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 22,BIOBANK 16",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTBAAAJ.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 14,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 23",
                "processed_sample_id": "BIOBANK 17",
                "cimac_id": "CTTTNFGJ5.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 23,BIOBANK 17",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTNFGJ5.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 29,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 24",
                "processed_sample_id": "BIOBANK 18",
                "cimac_id": "CTTTJUV7D.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 24,BIOBANK 18",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTJUV7D.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 5,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 25",
                "processed_sample_id": "BIOBANK 19",
                "cimac_id": "CTTT6JH4P.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 25,BIOBANK 19",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTT6JH4P.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 15,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 26",
                "processed_sample_id": "BIOBANK 20",
                "cimac_id": "CTTTBCBY3.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 26,BIOBANK 20",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTBCBY3.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 30,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 27",
                "processed_sample_id": "BIOBANK 21",
                "cimac_id": "CTTT6436N.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 27,BIOBANK 21",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTT6436N.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 6,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 28",
                "processed_sample_id": "BIOBANK 22",
                "cimac_id": "CTTT79UBR.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 28,BIOBANK 22",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTT79UBR.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 16,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 29",
                "processed_sample_id": "BIOBANK 23",
                "cimac_id": "CTTTMKZYJ.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 29,BIOBANK 23",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTMKZYJ.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 31,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 30",
                "processed_sample_id": "BIOBANK 24",
                "cimac_id": "CTTTZ5OF5.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 30,BIOBANK 24",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTZ5OF5.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 7,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 31",
                "processed_sample_id": "BIOBANK 25",
                "cimac_id": "CTTT98N6F.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 31,BIOBANK 25",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTT98N6F.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 17,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 32",
                "processed_sample_id": "BIOBANK 26",
                "cimac_id": "CTTT685SK.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 32,BIOBANK 26",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTT685SK.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 32,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 33",
                "processed_sample_id": "BIOBANK 27",
                "cimac_id": "CTTTBBNED.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 33,BIOBANK 27",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTBBNED.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 8,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 34",
                "processed_sample_id": "BIOBANK 28",
                "cimac_id": "CTTT7AGEG.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 34,BIOBANK 28",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTT7AGEG.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 18,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 35",
                "processed_sample_id": "BIOBANK 29",
                "cimac_id": "CTTTT174Q.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 35,BIOBANK 29",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTT174Q.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 34,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 36",
                "processed_sample_id": "BIOBANK 30",
                "cimac_id": "CTTTKWKBI.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 36,BIOBANK 30",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTKWKBI.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 9,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 37",
                "processed_sample_id": "BIOBANK 31",
                "cimac_id": "CTTTQ9WRK.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 37,BIOBANK 31",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTQ9WRK.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 19,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 38",
                "processed_sample_id": "BIOBANK 32",
                "cimac_id": "CTTTVLOU8.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 38,BIOBANK 32",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTTVLOU8.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 10,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 39",
                "processed_sample_id": "BIOBANK 33",
                "cimac_id": "CTTT3ZOQ5.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 39,BIOBANK 33",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTT3ZOQ5.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
            {
                "entry_number": 20,
                "collection_event_name": "Baseline",
                "cohort_name": "Arm_A",
                "participant_id": "LOCAL 40",
                "processed_sample_id": "BIOBANK 34",
                "cimac_id": "CTTT8YJ1I.01",
                "type_of_sample": "Tumor Tissue",
                "type_of_tumor_sample": "Metastatic Tumor",
                "sample_collection_procedure": "Core Biopsy",
                "fixation_or_stabilization_type": "Formalin-Fixed Paraffin-Embedded",
                "processed_sample_type": "h_and_e",
                "material_used_units": "Slides",
                "material_remaining_units": "Slides",
                "material_storage_condition": "4oC",
                "quality_of_sample": "Pass",
                "sample_replacement": "Replacement Not Requested",
                "sample_approved": True,
                "protocol_identifier": "test_trial",
                "manifest_id": "test_trial_H&E",
                "box_number": "X",
                "sample_location": "X",
                "sample_key": "test_trial,LOCAL 40,BIOBANK 34",
                "biobank_id": "biobank",
                "standardized_collection_event_name": "Baseline",
                "qc_comments": "",
                "sample_manifest_type": "tissue_h_and_e",
                "processed_sample_quantity": 1,
                "material_remaining": -1,
                "material_used": 1,
                "barcode": "CTTT8YJ1I.01",
                "excluded": False,
                "submitter": "user",
                "reason": "Create excluded field for existing Samples",
                "event": "manual_update",
                "modified_time": 1609459200 + 86400 * 2,
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "study_encoding": "TTT",
                "receiving_party": "DFCI_Hodi",
            },
        ],
        "status_log": [
            {
                "modified_timestamp": "2021-01-05T00:00:00Z",
                "status": "qc_complete",
                "submitter": "user",
            }
        ],
    }
)
samples.extend(manifests[-1]["samples"])
