"""empty message

Revision ID: 08591dac6d5c
Revises: 25503efafd95
Create Date: 2019-09-24 16:45:09.091526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08591dac6d5c'
down_revision = '25503efafd95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloadable_files', 'artifact_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloadable_files', sa.Column('artifact_category', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
