"""empty message

Revision ID: 0c924d67603c
Revises: dc82194b354b
Create Date: 2019-12-12 16:04:20.120627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c924d67603c"
down_revision = "dc82194b354b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "downloadable_files", sa.Column("crc32c_hash", sa.String(), nullable=True)
    )
    op.alter_column(
        "downloadable_files", "md5_hash", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: we deliberately leave md5_hash nullable.
    op.drop_column("downloadable_files", "crc32c_hash")
    # ### end Alembic commands ###
