"""empty message

Revision ID: 0d2290b6be02
Revises: 37888cac6b2b
Create Date: 2019-07-21 18:27:52.179930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d2290b6be02'
down_revision = '37888cac6b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_jobs',
    sa.Column('_created', sa.DateTime(), nullable=True),
    sa.Column('_updated', sa.DateTime(), nullable=True),
    sa.Column('_etag', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('started', 'completed', 'errored', name='job_statuses'), nullable=False),
    sa.Column('gcs_file_uris', postgresql.ARRAY(sa.String(), dimensions=1), nullable=False),
    sa.Column('metadata_json_patch', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uploader_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uploader_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('gcs_objects_idx', 'upload_jobs', ['gcs_file_uris'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('gcs_objects_idx', table_name='upload_jobs')
    op.drop_table('upload_jobs')
    # ### end Alembic commands ###
