"""empty message

Revision ID: 25503efafd95
Revises: 57879ca2d336
Create Date: 2019-09-24 16:23:58.445172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "25503efafd95"
down_revision = "57879ca2d336"
branch_labels = None
depends_on = None

artifact_category = postgresql.ENUM(
    "Assay Artifact from CIMAC",
    "Pipeline Artifact",
    "Manifest File",
    "Other",
    name="artifact_category",
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE downloadable_files ALTER COLUMN artifact_category TYPE text"
    )
    artifact_category.drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    artifact_category.create(op.get_bind())
    op.execute(
        "UPDATE downloadable_files SET artifact_category = 'Other' "
        "WHERE artifact_category NOT IN ('Assay Artifact from CIMAC', 'Pipeline Artifact', 'Manifest File')"
    )
    op.execute(
        "ALTER TABLE downloadable_files ALTER COLUMN artifact_category TYPE artifact_category"
    )
    # ### end Alembic commands ###
