"""empty message

Revision ID: 25503efafd95
Revises: 57879ca2d336
Create Date: 2019-09-24 16:23:58.445172

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "25503efafd95"
down_revision = "57879ca2d336"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE downloadable_files SET data_format = 'Shipping Manifest' WHERE artifact_category = 'Manifest File'"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE downloadable_files SET data_format = 'Shipping Manifest' WHERE artifact_category = 'Manifest File'"
    )
    op.execute(
        "UPDATE downloadable_files SET artifact_category = 'Assay Artifact from CIMAC' WHERE data_format NOT IN ('Shipping Manifest', 'Assay Metadata')"
    )
    op.execute(
        "UPDATE downloadable_files SET artifact_category = 'Manifest File' WHERE data_format = 'Shipping Manifest'"
    )
    op.execute(
        "UPDATE downloadable_files SET artifact_category = 'Other' WHERE data_format = 'Assay Metadata'"
    )
    # ### end Alembic commands ###
