"""empty message

Revision ID: 3ce942d942b7
Revises: 7df49a8d4792
Create Date: 2019-08-15 11:43:18.750886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ce942d942b7"
down_revision = "7df49a8d4792"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "downloadable_files",
        sa.Column("_created", sa.DateTime(), nullable=True),
        sa.Column("_updated", sa.DateTime(), nullable=True),
        sa.Column("_etag", sa.String(length=40), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum(
                "FASTA",
                "FASTQ",
                "TIFF",
                "VCF",
                "TSV",
                "Excel",
                "NPX",
                "BAM",
                "MAF",
                "PNG",
                "JPG",
                "XML",
                "Other",
                name="file_type",
            ),
            nullable=False,
        ),
        sa.Column("uploaded_timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "artifact_category",
            sa.Enum(
                "Assay Artifact from CIMAC",
                "Pipeline Artifact",
                "Manifest File",
                "Other",
                name="artifact_category",
            ),
            nullable=False,
        ),
        sa.Column(
            "assay_category",
            sa.Enum(
                "Whole Exome Sequencing (WES)",
                "RNASeq",
                "Conventional Immunohistochemistry",
                "Multiplex Immunohistochemistry",
                "Multiplex Immunofluorescence",
                "CyTOF",
                "OLink",
                "NanoString",
                "ELISpot",
                "Multiplexed Ion-Beam Imaging (MIBI)",
                "Other",
                "None",
                name="assay_category",
            ),
            nullable=False,
        ),
        sa.Column("md5_hash", sa.String(), nullable=False),
        sa.Column("trial_id", sa.String(), nullable=False),
        sa.Column("object_url", sa.String(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["trial_id"], ["trial_metadata.trial_id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "users",
        "disabled",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "disabled",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_table("downloadable_files")
    # ### end Alembic commands ###
