"""empty message

Revision ID: 46c8243113cb
Revises: d93c0ac0293e
Create Date: 2019-09-05 12:06:48.891539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "46c8243113cb"
down_revision = "d93c0ac0293e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "downloadable_files", sa.Column("data_format", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("downloadable_files", "data_format")
    # ### end Alembic commands ###
