"""empty message

Revision ID: 57cfbda10872
Revises: f324cdb1a846
Create Date: 2020-01-16 14:46:39.536797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "57cfbda10872"
down_revision = "f324cdb1a846"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "downloadable_files",
        sa.Column(
            "ihc_combined_plot", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("downloadable_files", "ihc_combined_plot")
    # ### end Alembic commands ###
