"""empty message

Revision ID: 5f70e6f7c0d9
Revises: facd42b8f277
Create Date: 2019-11-26 12:33:58.500682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5f70e6f7c0d9"
down_revision = "facd42b8f277"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "downloadable_files",
        sa.Column(
            "clustergrammer", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("downloadable_files", "clustergrammer")
    # ### end Alembic commands ###
