"""empty message

Revision ID: 6378d4ed779f
Revises: 3ce942d942b7
Create Date: 2019-08-28 11:57:30.879061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6378d4ed779f'
down_revision = '3ce942d942b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_jobs', sa.Column('assay_type', sa.String(), nullable=True))
    op.execute("UPDATE upload_jobs set assay_type='wes'")
    op.alter_column('upload_jobs', 'assay_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_jobs', 'assay_type')
    # ### end Alembic commands ###
