"""empty message

Revision ID: 65a3e6120a95
Revises: 37436458bc78
Create Date: 2020-07-16 11:31:20.995322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a3e6120a95'
down_revision = '37436458bc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_jobs', 'gcs_xlsx_uri',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
         "UPDATE upload_jobs SET gcs_xlsx_uri = '' WHERE gcs_xlsx_uri is null"
    )
    op.alter_column('upload_jobs', 'gcs_xlsx_uri',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
