"""empty message

Revision ID: 66897499754f
Revises: 9f423e8a1d69
Create Date: 2019-09-11 15:42:10.933195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "66897499754f"
down_revision = "9f423e8a1d69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("permissions", "mode")
    op.alter_column(
        "permissions",
        "assay_type",
        existing_type=sa.Enum(
            "Whole Exome Sequencing (WES)",
            "RNASeq",
            "Conventional Immunohistochemistry",
            "Multiplex Immunohistochemistry",
            "Multiplex Immunofluorescence",
            "CyTOF",
            "OLink",
            "NanoString",
            "ELISpot",
            "Multiplexed Ion-Beam Imaging (MIBI)",
            "Other",
            "None",
            name="assay_category",
        ),
        type_=sa.String(),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permissions",
        sa.Column(
            "mode",
            postgresql.ENUM("read", "write", name="mode"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "permissions",
        "assay_type",
        existing_type=sa.String(),
        type_=sa.Enum(
            "Whole Exome Sequencing (WES)",
            "RNASeq",
            "Conventional Immunohistochemistry",
            "Multiplex Immunohistochemistry",
            "Multiplex Immunofluorescence",
            "CyTOF",
            "OLink",
            "NanoString",
            "ELISpot",
            "Multiplexed Ion-Beam Imaging (MIBI)",
            "Other",
            "None",
            name="assay_category",
        ),
    )
    # ### end Alembic commands ###
