"""empty message

Revision ID: 6a35ce2160ad
Revises: 0d2290b6be02
Create Date: 2019-07-21 18:33:31.630948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a35ce2160ad'
down_revision = '0d2290b6be02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_jobs', 'uploader_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('upload_jobs_uploader_email_fkey', 'upload_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'upload_jobs', 'users', ['uploader_email'], ['email'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upload_jobs', type_='foreignkey')
    op.create_foreign_key('upload_jobs_uploader_email_fkey', 'upload_jobs', 'users', ['uploader_email'], ['email'])
    op.alter_column('upload_jobs', 'uploader_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
