"""optional data_format and file_name

Revision ID: 7d3ad965db30
Revises: 509970372467
Create Date: 2021-04-12 15:32:30.766751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d3ad965db30"
down_revision = "509970372467"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "downloadable_files", "data_format", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "downloadable_files", "file_name", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "downloadable_files", "file_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "downloadable_files", "data_format", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
