"""empty message

Revision ID: 7df49a8d4792
Revises: 6a35ce2160ad
Create Date: 2019-08-09 09:17:14.197231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7df49a8d4792"
down_revision = "6a35ce2160ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("_created", sa.DateTime(), nullable=True),
        sa.Column("_updated", sa.DateTime(), nullable=True),
        sa.Column("_etag", sa.String(length=40), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("granted_by_user", sa.Integer(), nullable=True),
        sa.Column("granted_to_user", sa.Integer(), nullable=True),
        sa.Column("trial_id", sa.String(), nullable=False),
        sa.Column(
            "assay_type",
            sa.Enum(
                "cytof",
                "mif",
                "micsss",
                "olink",
                "rna expression",
                "wes",
                name="assays",
            ),
            nullable=False,
        ),
        sa.Column("mode", sa.Enum("read", "write", name="mode"), nullable=True),
        sa.ForeignKeyConstraint(["granted_by_user"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["granted_to_user"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["trial_id"], ["trial_metadata.trial_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_permissions_granted_to_user"),
        "permissions",
        ["granted_to_user"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permissions_trial_id"), "permissions", ["trial_id"], unique=False
    )
    op.add_column(
        "users",
        sa.Column("disabled", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column("users", sa.Column("approval_date", sa.DateTime(), nullable=True))

    roles = sa.Enum(
        "cidc-admin",
        "cidc-biofx-user",
        "cimac-biofx-user",
        "cimac-user",
        "developer",
        "devops",
        "nci-biobank-user",
        name="roles",
    )
    roles.create(op.get_bind())

    op.add_column("users", sa.Column("role", roles, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.drop_column("users", "registration_approved")
    op.drop_column("users", "approval_date")
    op.drop_column("users", "disabled")
    op.drop_index(op.f("ix_permissions_trial_id"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_granted_to_user"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
