"""empty message

Revision ID: 9f423e8a1d69
Revises: 46c8243113cb
Create Date: 2019-09-10 13:31:20.052103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9f423e8a1d69"
down_revision = "46c8243113cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "manifest_uploads", sa.Column("manifest_type", sa.String(), nullable=False)
    )
    op.add_column(
        "manifest_uploads",
        sa.Column(
            "metadata_patch", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    op.drop_column("manifest_uploads", "manifest_patch")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "manifest_uploads",
        sa.Column(
            "manifest_patch",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("manifest_uploads", "metadata_patch")
    op.drop_column("manifest_uploads", "manifest_type")
    # ### end Alembic commands ###
