"""empty message

Revision ID: e2744508442a
Revises: 37436458bc78
Create Date: 2020-07-10 09:48:11.174695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e2744508442a"
down_revision = "37436458bc78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "upload_jobs",
        sa.Column(
            "token",
            postgresql.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upload_jobs", "token")
    # ### end Alembic commands ###
