"""empty message

Revision ID: e75f457b5b82
Revises: 6dc3f2e63558
Create Date: 2020-04-09 17:32:24.779716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e75f457b5b82"
down_revision = "6dc3f2e63558"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_perms", "permissions", ["granted_to_user", "trial_id", "upload_type"]
    )
    op.alter_column(
        "upload_jobs", "uploader_email", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "upload_jobs", "uploader_email", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint("unique_perms", "permissions", type_="unique")
    # ### end Alembic commands ###
