"""empty message

Revision ID: ebe83ddd1ba3
Revises: d82f2d53d8ba
Create Date: 2019-09-03 19:48:12.658448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebe83ddd1ba3'
down_revision = 'd82f2d53d8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### assay_uploads should be TRUNCATED beforehand ###
    op.add_column('assay_uploads', sa.Column('gcs_file_uuids', postgresql.ARRAY(sa.String(), dimensions=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assay_uploads', 'gcs_file_uuids')
    # ### end Alembic commands ###
